const italyTrivia = [
  "The Italian flag colors (green, white, and red) represent hope, faith, and charity!",
  "Italy has the most UNESCO World Heritage Sites of any country - 58 in total!",
  "Italians invented pizza in Naples, around the 1700s. The classic Margherita pizza was named after Queen Margherita of Italy!",
  "The Vespa scooter was designed after World War II and became an Italian icon. The name means 'wasp' in Italian!",
  "The Italian city of Venice is built on 118 small islands connected by about 400 bridges!",
  "Italy is shaped like a boot kicking a triangle (Sicily)!",
  "The Vatican City, located within Rome, is the smallest country in the world!",
  "Romans were the first to have shopping malls about 2,000 years ago!",
  "The University of Bologna in Italy is the oldest university in the world, founded in 1088!",
  "Italian is a Romance language derived from Latin!",
  "The Ferrari, one of the world's most famous sports cars, is made in Italy!",
  "Rome's Colosseum could hold up to 50,000 spectators for gladiator fights!",
  "Italians invented gelato, which has less fat than regular ice cream!",
  "The Leaning Tower of Pisa took 199 years to build and started leaning during construction!",
  "Italy has three active volcanoes: Vesuvius, Etna, and Stromboli!",
  "The average Italian consumes 25 kilograms of pasta per year!",
  "Leonardo da Vinci, the famous artist and inventor, was born in Italy!",
  "The Italian police force uses Lamborghinis as patrol cars on highways!",
  "Italians invented the piano, thermometer, and the telephone!",
  "The longest river in Italy is the Po, which is 652 kilometers long!",
  "Italy has been making wine for over 4,000 years!",
  "The Italian word 'ciao' meaning both hello and goodbye comes from a Venetian phrase meaning 'I am your slave'!",
  "Italian espresso is so important there are certified technicians who test espresso quality!",
  "Romans built over 53,000 miles of roads throughout their empire!",
  "Michelangelo spent four years painting the ceiling of the Sistine Chapel... lying on his back!",
  "The Italian city of Pompeii was perfectly preserved when Mount Vesuvius erupted in 79 AD!",
  "The fork was introduced as an eating utensil in Italy during the 11th century!",
  "Italy is the largest producer of wine in the world!",
  "The Bank of Italy was founded in 1893 and is one of the oldest banks in the world!",
  "Every coin thrown into Rome's Trevi Fountain (about €3,000 daily) is collected and donated to charity!",
  "The first eyeglasses were invented in Italy around 1286!"
];

export default italyTrivia;
